/**
 * DocTextEngine tests: paragraph splitting (pure) and — when a real binary
 * .doc fixture exists (generated by scripts/makeFixtures.mjs on macOS) —
 * end-to-end extraction via word-extractor.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { splitBodyParagraphs } from "../src/formats/doc/docTextEngine";

describe("splitBodyParagraphs", () => {
	it("splits CR-separated Word body text", () => {
		expect(splitBodyParagraphs("一\r二\r\n三\n四")).toEqual([
			"一",
			"二",
			"三",
			"四",
		]);
	});

	it("drops leading and trailing empty lines, keeps interior ones", () => {
		expect(splitBodyParagraphs("\r\r内容\r\r")).toEqual(["", "内容", ""]);
		expect(splitBodyParagraphs("内容\r")).toEqual(["内容"]);
	});
});

describe("DocTextEngine.load (real fixture)", () => {
	const fixture = join(
		__dirname,
		"..",
		"..",
		"debug-vault",
		"test-sample.doc",
	);
	const itIfFixture = existsSync(fixture) ? it : it.skip;

	itIfFixture("extracts paragraphs via word-extractor", async () => {
		const { DocTextEngine } = await import(
			"../src/formats/doc/docTextEngine"
		);
		const engine = await DocTextEngine.load(new Uint8Array(readFileSync(fixture)));
		expect(engine.kind).toBe("doc");
		expect(engine.paragraphs.length).toBeGreaterThanOrEqual(3);
		const all = engine.paragraphs.join("\n");
		expect(all).toContain("第一段");
		expect(all).toContain("第二段");
		expect(all).toContain("第三段");
	});
});
